apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: import_demo_service
  description: "example used to show off import woohoo!"
  tags:
    - first
    - two+words
    - bs-one-tag
    - the-cool-tag
    - andAnotherOne
  labels:
    imma: label
spec:
  type: service
  lifecycle: generally available
  owner: Frontend
